output:
  sort-results: true

run:
  go: "1.23.4"
  timeout: 10m

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Ignore check: Packages must have a package comment
    - text: "ST1000: at least one file in a package should have a package comment"
      linters:
        - stylecheck

linters:
  disable-all: true
  enable:
    - gofumpt
    - stylecheck
    - staticcheck
    - errorlint

linters-settings:
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all"]
  errorlint:
    # https://github.com/polyfloyd/go-errorlint
    # Check whether fmt.Errorf uses the %w verb for formatting errors.
    errorf: true
    # Check for plain type assertions and type switches (errors.As must be used).
    asserts: true
    # Check for plain error comparisons (errors.Is must be used)
    comparison: true
