apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: aks
spec:
  version: {{ .TagName }}
  homepage: https://github.com/Azure/kubectl-aks
  shortDescription: Interact with and debug AKS clusters
  description: |
    This plugin provides a set of commands that enable users to interact with an
    AKS cluster even when the control plane is not functioning as expected. For
    example, users can still use the plugin to debug their cluster if the API
    server is not working correctly. This plugin allows users to perform various
    tasks, retrieve information, and execute commands against the cluster nodes,
    regardless of the control plane's state.

    It's important to note that this plugin does not replace az (the Azure CLI
    [1]). Instead, it complements it by offering additional commands and
    providing users with a kubectl-like experience. In practice, users will use
    az to create and delete their AKS cluster, and then use kubectl and
    kubectl-aks to interact with and debug it.

    [1] https://learn.microsoft.com/en-us/cli/azure/
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/Azure/kubectl-aks/releases/download/{{ .TagName }}/kubectl-aks-linux-amd64-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-aks
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/Azure/kubectl-aks/releases/download/{{ .TagName }}/kubectl-aks-darwin-amd64-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-aks
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/Azure/kubectl-aks/releases/download/{{ .TagName }}/kubectl-aks-darwin-arm64-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-aks
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/Azure/kubectl-aks/releases/download/{{ .TagName }}/kubectl-aks-windows-amd64-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-aks.exe
